## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [3]:
gp = titanic_df.groupby('Pclass')

In [4]:
for group, data in gp:
    avg_age = data['Age'].mean()
    missing_age = data['Age'].isna().sum()
    print(f"Pclass {group}: Avg Age {avg_age:.2f}, Missing Ages {missing_age}")

Pclass 1: Avg Age 38.23, Missing Ages 30
Pclass 2: Avg Age 29.88, Missing Ages 11
Pclass 3: Avg Age 25.14, Missing Ages 136

In [5]:
pclass_groups = titanic_df.groupby("Pclass")

for group, data in pclass_groups:
    avg_age = data['Age'].mean()
    missing_age = data['Age'].isna().sum()
    print(f"Pclass {group}: Avg Age {avg_age:.2f}, Missing Ages {missing_age}")

Pclass 1: Avg Age 38.23, Missing Ages 30
Pclass 2: Avg Age 29.88, Missing Ages 11
Pclass 3: Avg Age 25.14, Missing Ages 136

In [6]:
gp['Age'].apply(lambda x: x.isna().sum())

Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

In [7]:
result = titanic_df.groupby("Pclass")['Age'].agg(
    Avg_Age='mean',
    Missing_Age=lambda x: x.isna().sum(),
    max_age = 'max',
    min_age = 'min'
)

print(result)

          Avg_Age  Missing_Age  max_age  min_age
Pclass
1       38.233441           30     80.0     0.92
2       29.877630           11     70.0     0.67
3       25.140620          136     74.0     0.42

In [8]:
result = titanic_df.groupby("Pclass")['Embarked'].agg(
    # Avg_Age='mean',
    Missing_Age=lambda x: x.isna().sum(),
    # max_age = 'max',
    # min_age = 'min'
)

print(result)
titanic_df.groupby("Pclass").count()

        Missing_Age
Pclass
1                 2
2                 0
3                 0

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,,,
1,216,216,216,216,186,216,216,216,216,176,214
2,184,184,184,184,173,184,184,184,184,16,184
3,491,491,491,491,355,491,491,491,491,12,491

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [9]:
for group, data in gp:
    mode_value = data['Embarked'].mode()[0]
    data['Embarked'] = data['Embarked'].fillna(mode_value)

    counts = data['Embarked'].value_counts().sort_values(ascending=True)
    print(f"Pclass {group}:\n{counts}\n")

Pclass 1:
Embarked
Q      2
C     85
S    129
Name: count, dtype: int64

Pclass 2:
Embarked
Q      3
C     17
S    164
Name: count, dtype: int64

Pclass 3:
Embarked
C     66
Q     72
S    353
Name: count, dtype: int64

In [13]:
gp['Embarked'] = gp.groupby('Pclass')['Embarked']\
                   .transform(lambda x: x.fillna(x.mode()[0]))
print(gp.groupby('Pclass')['Embarked']
      .value_counts()
      .sort_values(ascending=True))

AttributeError: 'DataFrameGroupBy' object has no attribute 'groupby'

In [9]:
for group, data in gp:
    mode_value = data['Embarked'].mode()[0]
    print(mode_value)

S
S
S

In [10]:
# code here inplace = False
for group in list(gp.groups.keys()):
    mode = gp.get_group(group)["Embarked"].mode()
    gp.get_group(group)["Embarked"].fillna(mode)
    print(gp.get_group(group)["Embarked"].value_counts(ascending = True))

Embarked
Q      2
C     85
S    127
Name: count, dtype: int64
Embarked
Q      3
C     17
S    164
Name: count, dtype: int64
Embarked
C     66
Q     72
S    353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [14]:
result = (
    titanic_df
    .groupby(['Embarked', 'Pclass'])['Fare']
    .mean()
    .round(2)
    .unstack()
    .to_dict('index')
)

result

{'C': {1: 104.72, 2: 25.36, 3: 11.21},
 'Q': {1: 90.0, 2: 12.35, 3: 11.18},
 'S': {1: 70.36, 2: 20.33, 3: 14.64}}

In [13]:
result = {}
embarked_group = titanic_df.groupby('Embarked')
for e_group, e_data in embarked_group:
    result[e_group] = {}
    pclass_group = e_data.groupby('Pclass')

    for p_group, p_data in pclass_group:
        result[e_group][p_group] =float(round(p_data['Fare'].mean(),2))
result

{'C': {1: 104.72, 2: 25.36, 3: 11.21},
 'Q': {1: 90.0, 2: 12.35, 3: 11.18},
 'S': {1: 70.36, 2: 20.33, 3: 14.64}}

In [14]:
list = ['a','b','c']
result = {}
for outer in list:
    result[outer] = {}
    for iner in range(1,4):
        result[outer][iner] = iner*10

result

{'a': {1: 10, 2: 20, 3: 30},
 'b': {1: 10, 2: 20, 3: 30},
 'c': {1: 10, 2: 20, 3: 30}}

In [15]:
dic = {}
dic['a'] = {}
dic['a'][1] = 10
dic

{'a': {1: 10}}

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

In [11]:
fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [12]:
fifa_df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,516,419,24,3,5,28,4,0

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [13]:
def z_norm(group,cols_to_perform):
    for col in cols_to_perform:
        mean = group[col].mean()
        std = group[col].std()
        group[f'{col} +_z_norm'] = (group[col] - mean) / std
    return group
cols = ["Passes	", "Passes Completed", "Crosses", "Crosses Completed"]

groups = fifa_df.groupby('Team')
group.apply(Z_norm,cols_to_perform = cols)

AttributeError: 'int' object has no attribute 'apply'

In [14]:
def z_normalization(group, cols_to_perform):
    for col in cols_to_perform:
        mean = group[col].mean()
        std = group[col].std()
        group[col + "_z"] = (group[col] - mean) / std
    return group
cols = ["Passes", "Passes Completed", "Crosses", "Crosses Completed"]
df_z = fifa_df.groupby("Team").apply(
    z_normalization,
    cols_to_perform=cols
)
summary = fifa_df.groupby("Team").agg(
    min_passes=("Passes", "min"),
    max_passes=("Passes", "max"),
    
    min_yellow_cards=("Yellow Cards", "min"),
    max_yellow_cards=("Yellow Cards", "max"),
    avg_yellow_cards=("Yellow Cards", "mean"),
    
    max_attempted_line_breaks=("Attempted Line Breaks", "max"),
    min_attempted_line_breaks=("Attempted Line Breaks", "min"),
    std_attempted_line_breaks=("Attempted Line Breaks", "std"),
    
    avg_possession=("Possession (%)", "mean")
)

C:\Users\HP\AppData\Local\Temp\ipykernel_1892\3561173601.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_z = fifa_df.groupby("Team").apply(

In [15]:
df_z = fifa_df.groupby("Team").apply(
    z_normalization,
    cols_to_perform=cols,
    include_groups=False
)

summary = fifa_df.groupby("Team").agg(
    min_passes=("Passes", "min"),
    max_passes=("Passes", "max"),
    min_yellow_cards=("Yellow Cards", "min"),
    max_yellow_cards=("Yellow Cards", "max"),
    avg_yellow_cards=("Yellow Cards", "mean"),
    max_attempted_line_breaks=("Attempted Line Breaks", "max"),
    min_attempted_line_breaks=("Attempted Line Breaks", "min"),
    std_attempted_line_breaks=("Attempted Line Breaks", "std"),
    avg_possession=("Possession (%)", "mean")
)
summary

,min_passes,max_passes,min_yellow_cards,max_yellow_cards,avg_yellow_cards,max_attempted_line_breaks,min_attempted_line_breaks,std_attempted_line_breaks,avg_possession
Team,,,,,,,,,
Argentina,408,862,0,8,2.285714,249,141,38.774685,49.285714
Australia,286,466,0,3,1.750000,171,133,17.682383,31.250000
Belgium,512,685,1,3,1.666667,195,167,14.422205,49.000000
Brazil,548,695,0,3,1.200000,193,164,10.691118,50.400000
Cameroon,295,500,1,5,2.666667,182,144,19.857828,38.333333
Canada,448,536,2,4,2.666667,176,102,37.753587,44.333333
Costa Rica,231,454,1,3,2.000000,154,86,38.974351,27.333333
Croatia,461,724,0,2,1.142857,259,97,54.499891,47.428571
Denmark,537,650,1,2,1.666667,241,173,34.000000,51.333333
Ecuador,429,484,0,2,1.000000,177,143,17.009801,42.666667
England,508,810,0,1,0.200000,208,133,29.676590,57.200000
France,358,734,0,3,1.142857,179,126,21.407609,44.857143
Germany,352,827,0,3,1.000000,256,143,56.624494,53.000000
Ghana,319,460,2,4,2.666667,188,122,33.020196,37.000000
Iran,232,463,2,3,2.333333,195,56,77.526340,31.666667
Japan,225,591,0,3,1.500000,253,104,64.048810,30.250000
Korea Republic,359,548,1,2,1.500000,201,139,27.072434,42.250000
Mexico,356,500,1,4,2.333333,198,127,40.706265,46.666667
Morocco,229,583,0,3,1.285714,157,128,10.641339,34.285714
Netherlands,403,786,0,4,1.800000,198,168,12.759310,44.000000
Poland,303,466,1,3,1.750000,156,79,36.326070,32.000000
Portugal,461,678,0,3,1.200000,197,165,13.049904,53.800000
Qatar,424,457,0,4,2.333333,174,159,7.767453,39.333333
Saudi Arabia,267,560,2,6,4.666667,205,147,29.022979,36.666667
Senegal,277,511,1,3,1.750000,184,143,16.938615,38.500000
Serbia,403,513,2,7,4.000000,184,140,22.188586,42.666667
Spain,647,1070,0,1,0.500000,237,186,24.289916,67.000000
Switzerland,403,512,1,4,2.250000,178,157,9.032349,43.000000
Tunisia,328,501,1,3,1.666667,200,153,24.419937,38.666667
United States,427,572,0,4,1.250000,204,143,27.693260,47.000000
Uruguay,390,528,1,3,2.000000,186,146,22.030282,41.000000
Wales,325,508,1,2,1.666667,208,104,53.028294,41.000000

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

In [16]:
balls = pd.read_csv("ipl_deliveries.csv")
balls.head(5)

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

### `Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [17]:
# filter data
f_balls = balls[balls['innings'] == 2]
batsman = f_balls.groupby(['ID','batter'])['batsman_run'].sum().sort_values(ascending=False)
batsman.head(1)

ID      batter
501206  PC Valthaty    120
Name: batsman_run, dtype: int64

In [45]:
# code here
#1
df = balls[balls.innings == 2]
df.groupby(["ID", "batter"]).sum().sort_values(by = "batsman_run", ascending = False)["batsman_run"].head()

ID       batter
501206   PC Valthaty      120
1254061  SV Samson        119
501243   V Sehwag         119
1136620  SR Watson        117
336018   ST Jayasuriya    114
Name: batsman_run, dtype: int64

In [54]:
df.groupby(['ID','batter'])['batsman_run'].sum().sort_values(ascending=False).head(1)

ID      batter
501206  PC Valthaty    120
Name: batsman_run, dtype: int64

In [18]:
df = balls[balls['innings'] == 2]

highest_score_chasing = (
    df.groupby(['ID', 'batter'])['batsman_run']
      .sum()
      .sort_values(ascending=False)
      .head(1)
)

highest_score_chasing

ID      batter
501206  PC Valthaty    120
Name: batsman_run, dtype: int64

In [19]:
df['extra_type'].unique()

array([nan, 'wides', 'legbyes', 'byes', 'noballs', 'penalty'],
      dtype=object)

In [20]:
# overall
# Best Strike rate while chasing and have faced 100+ balls
# Chasing mean team batting in second inning
df = df[df['extra_type'] != 'wides']
temp_df = df.groupby('batter').agg({
    'batsman_run':'sum',
    'ballnumber':'count'
})
temp_df['strike_rate'] = (temp_df['batsman_run'] / temp_df['ballnumber'])*100
temp_df = temp_df[temp_df['ballnumber'] > 100]
top5_striker = temp_df.sort_values(by='strike_rate',ascending=False).reset_index().head()
top5_striker

           batter  batsman_run  ballnumber  strike_rate
0      PJ Cummins          222         114   194.736842
1      AD Russell          986         570   172.982456
2  LS Livingstone          182         107   170.093458
3       SP Narine          599         356   168.258427
4      SO Hetmyer          330         200   165.000000

In [21]:
# par match
# Best Strike rate while chasing and have faced 100+ balls
# Chasing mean team batting in second inning
df = df[df['extra_type'] != 'wides']
temp_df = df.groupby(['ID','batter']).agg({
    'batsman_run':'sum',
    'ballnumber':'count'
})
temp_df
temp_df['strike_rate'] = (temp_df['batsman_run'] / temp_df['ballnumber'])*100
temp_df

temp_df = temp_df[temp_df['ballnumber'] > 50]
temp_df
top5_striker = temp_df.sort_values(by='strike_rate',ascending=False).reset_index().head()
top5_striker

        ID      batter  batsman_run  ballnumber  strike_rate
0   501243    V Sehwag          119          56   212.500000
1   980921   Q de Kock          108          51   211.764706
2  1136620   SR Watson          117          57   205.263158
3   548329   DA Warner          109          54   201.851852
4  1254073  D Padikkal          101          52   194.230769

### `Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [22]:
balls['isWicketDelivery'].unique()

array([0, 1])

In [23]:
balls['is_batter_out'] = balls['batter'] == balls['player_out']
balls

temp_df = balls.groupby(['batter','bowler']).agg({
    'is_batter_out':'sum',
    'batsman_run':'sum'
})
temp_df.sort_values(by=['is_batter_out','batsman_run'],ascending=[False,True])

                           is_batter_out  batsman_run
batter     bowler
MS Dhoni   Z Khan                      7           74
V Kohli    Sandeep Sharma              7           78
RG Sharma  A Mishra                    7           87
RV Uthappa R Ashwin                    7          123
RG Sharma  SP Narine                   7          137
...                                  ...          ...
N Rana     R Ashwin                    0           99
SR Watson  Sandeep Sharma              0          102
KD Karthik JD Unadkat                  0          104
SA Yadav   R Ashwin                    0          106
KL Rahul   DL Chahar                   0          120

[24213 rows x 2 columns]

### `Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [24]:
pair = balls.groupby(['batter','non-striker'])['total_run'].sum().sort_values(ascending=False).head()
pair

batter          non-striker
AB de Villiers  V Kohli           1623
CH Gayle        V Kohli           1617
V Kohli         AB de Villiers    1511
DA Warner       S Dhawan          1420
V Kohli         CH Gayle          1185
Name: total_run, dtype: int64

In [26]:
pair = balls.copy()

# Create a sorted tuple so (A,B) and (B,A) become same
pair['pair'] = pair.apply(
    lambda x: tuple(sorted([x['batter'], x['non-striker']])), axis=1
)

# Group by this new pair column
result = (
    pair.groupby('pair')['total_run']
    .sum()
    .sort_values(ascending=False)
    .head()
)

print(result)

pair
(AB de Villiers, V Kohli)    3134
(CH Gayle, V Kohli)          2802
(DA Warner, S Dhawan)        2357
(G Gambhir, RV Uthappa)      1906
(KL Rahul, MA Agarwal)       1731
Name: total_run, dtype: int64

### `Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [112]:
balls.head(1)

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,is_batter_out
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans,False

In [122]:
data = balls.groupby(['batter','non-striker'])['total_run'].sum().sort_values(ascending=False)
data

batter          non-striker
AB de Villiers  V Kohli           1623
CH Gayle        V Kohli           1617
V Kohli         AB de Villiers    1511
DA Warner       S Dhawan          1420
V Kohli         CH Gayle          1185
                                  ...
PP Ojha         Shoaib Ahmed         0
YV Takawale     Yuvraj Singh         0
SN Khan         MA Starc             0
SN Thakur       LH Ferguson          0
                MK Tiwary            0
Name: total_run, Length: 8062, dtype: int64

In [27]:
pair = balls.groupby(['batter','non-striker'])['total_run'].sum()
pair

batter          non-striker
A Ashish Reddy  A Mishra           19
                AA Jhunjhunwala     3
                CL White            3
                DB Ravi Teja        6
                DJG Sammy          26
                                   ..
Z Khan          S Aravind           0
                S Nadeem            3
                SL Malinga         17
                SR Tendulkar        2
                SS Tiwary          21
Name: total_run, Length: 8062, dtype: int64

In [130]:
# Make a copy
df = balls.copy()

# Create order-independent batting pairs
df["Batsman1"] = df[["batter", "non-striker"]].min(axis=1)
df["Batsman2"] = df[["batter", "non-striker"]].max(axis=1)
# Aggregate partnership stats
pair_df = df.groupby(["Batsman1", "Batsman2"]).agg(
    Runs=("total_run", "sum"),
    Balls=("ballnumber", "count"),   # wides counted as allowed
    Innings=("ID", "nunique")
).reset_index()


# Calculate Average & Strike Rate
pair_df["Avg"] = pair_df["Runs"] / pair_df["Innings"]
pair_df["StrikeRate"] = (pair_df["Runs"] / pair_df["Balls"]) * 100

# Final result
pair_df = pair_df.sort_values("Runs", ascending=False)
pair_df


# pair_df[["Batsman1", "Batsman2", "Runs", "Avg", "StrikeRate"]]

            Batsman1    Batsman2  Runs  Balls  Innings        Avg  StrikeRate
302   AB de Villiers     V Kohli  3134   2059       77  40.701299  152.209811
1251        CH Gayle     V Kohli  2802   1973       60  46.700000  142.017233
1508       DA Warner    S Dhawan  2357   1725       50  47.140000  136.637681
1954       G Gambhir  RV Uthappa  1906   1425       48  39.708333  133.754386
2803        KL Rahul  MA Agarwal  1731   1211       33  52.454545  142.939719
...              ...         ...   ...    ...      ...        ...         ...
2990       LPC Silva   RG Sharma     0      6        2   0.000000    0.000000
2508       JO Holder    KL Rahul     0      2        1   0.000000    0.000000
26        A Chandila     OA Shah     0      1        1   0.000000    0.000000
4107        SK Warne     SW Tait     0      1        1   0.000000    0.000000
4203    Shoaib Ahmed    TL Suman     0      1        1   0.000000    0.000000

[4259 rows x 7 columns]

In [28]:
c_balls = balls.copy()
c_balls['batsman1'] = c_balls[['batter','non-striker']].min(axis=1)
c_balls['batsman2'] = c_balls[['batter','non-striker']].max(axis=1)
c_balls
pair_data = c_balls.groupby(['batsman1','batsman2']).agg(
    Runs = ('total_run','sum'),
    balls = ('ballnumber','count'),
    inning = ('ID','nunique')
).reset_index()
pair_data['Avg'] = (pair_data['Runs'] / pair_data['inning'])
pair_data['strike_rate'] = (pair_data['Runs'] / pair_data['balls'])*100
data = pair_data[['batsman1','batsman2','Runs','Avg','strike_rate']].sort_values(by='Runs',ascending=False).round(2)
data=data.reset_index(drop=True)
data.head(50)

          batsman1       batsman2  Runs    Avg  strike_rate
0   AB de Villiers        V Kohli  3134  40.70       152.21
1         CH Gayle        V Kohli  2802  46.70       142.02
2        DA Warner       S Dhawan  2357  47.14       136.64
3        G Gambhir     RV Uthappa  1906  39.71       133.75
4         KL Rahul     MA Agarwal  1731  52.45       142.94
5         CH Gayle       KL Rahul  1633  44.14       135.18
6         MS Dhoni       SK Raina  1482  26.95       137.99
7          PP Shaw       S Dhawan  1461  33.20       141.16
8        DA Warner    JM Bairstow  1401  56.04       144.28
9          RR Pant        SS Iyer  1368  36.00       129.18
10         M Vijay     MEK Hussey  1367  39.06       119.18
11     BB McCullum       DR Smith  1363  34.95       134.42
12      KA Pollard      RG Sharma  1344  29.87       154.66
13        MS Dhoni      RA Jadeja  1290  24.34       141.91
14       Q de Kock      RG Sharma  1274  34.43       130.53
15       AM Rahane      SR Watson  1169  40.31       132.84
16      MEK Hussey       SK Raina  1168  40.28       137.57
17       AT Rayudu      RG Sharma  1165  30.66       116.27
18      JC Buttler      SV Samson  1147  34.76       144.64
19       AM Rahane       R Dravid  1145  35.78       112.04
20    F du Plessis       SK Raina  1056  31.06       123.51
21       MK Pandey     RV Uthappa  1040  31.52       118.45
22       AT Rayudu     KA Pollard  1023  29.23       155.24
23     BB McCullum       SK Raina   976  36.15       142.07
24       G Gambhir      JH Kallis   961  29.12       115.23
25       AM Rahane      SV Samson   957  39.88       125.10
26      D Padikkal        V Kohli   946  43.00       127.32
27       G Gambhir       V Sehwag   933  33.32       151.22
28    AC Gilchrist       HH Gibbs   921  35.42       130.45
29       HH Pandya     KA Pollard   919  25.53       163.23
30        CH Gayle     TM Dilshan   909  45.45       140.06
31   KS Williamson       S Dhawan   898  47.26       138.58
32    F du Plessis     RD Gaikwad   894  42.57       126.81
33    Ishan Kishan      RG Sharma   875  35.00       130.40
34        S Dhawan        SS Iyer   868  41.33       125.98
35     LMP Simmons       PA Patel   854  44.95       130.18
36    F du Plessis      SR Watson   846  38.45       121.03
37     S Badrinath       SK Raina   820  34.17       128.93
38        DJ Bravo       MS Dhoni   818  23.37       150.64
39       G Gambhir      MK Pandey   812  32.48       134.21
40       AT Rayudu       MS Dhoni   800  42.11       141.84
41    Ishan Kishan       SA Yadav   788  31.52       128.55
42       DA Warner      MK Pandey   787  60.54       130.73
43       DA Warner       V Sehwag   765  23.91       146.83
44    SR Tendulkar  ST Jayasuriya   752  35.81       128.99
45       AT Rayudu      SR Watson   748  37.40       138.01
46        R Dravid      SR Watson   745  46.56       128.45
47        DR Smith       SK Raina   739  28.42       145.47
48         CA Lynn      SP Narine   731  28.12       168.82
49       AM Rahane      SPD Smith   719  39.94       125.26

In [29]:

c_balls = balls.copy()
c_balls['batsman1'] = c_balls[['batter','non-striker']].min(axis=1)
c_balls['batsman2'] = c_balls[['batter','non-striker']].max(axis=1)
c_balls
pair_data = c_balls.groupby(['batsman1','batsman2']).agg(
    Runs = ('total_run','sum'),
    balls = ('ballnumber','count'),
    inning = ('ID','nunique')
).reset_index()
pair_data.sort_values(by='Runs', ascending=False)

            batsman1    batsman2  Runs  balls  inning
302   AB de Villiers     V Kohli  3134   2059      77
1251        CH Gayle     V Kohli  2802   1973      60
1508       DA Warner    S Dhawan  2357   1725      50
1954       G Gambhir  RV Uthappa  1906   1425      48
2803        KL Rahul  MA Agarwal  1731   1211      33
...              ...         ...   ...    ...     ...
2990       LPC Silva   RG Sharma     0      6       2
2508       JO Holder    KL Rahul     0      2       1
26        A Chandila     OA Shah     0      1       1
4107        SK Warne     SW Tait     0      1       1
4203    Shoaib Ahmed    TL Suman     0      1       1

[4259 rows x 5 columns]